# Use docker-based build environment (instead of openvz)
sudo: false

language: java

# Cache eclipse
cache:
  directories:
    - '$HOME/eclipse-relang'

before_install: 
  - chmod +x './scripts/download_eclipse.sh'
  - './scripts/download_eclipse.sh'
install: ant make-stable-p2
script: true